name: test
run-name: Release - ${{ github.event.head_commit.message }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
on:
  push:
    branches:
    - master
    - test
  pull_request:
    branches:
    - master
  schedule:
  - cron: '15 */12 * * *'
  workflow_dispatch: {}
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        wget -qO- "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/raw/$GITHUB_SHA/.github/release" |
          sh -es || :
